name: Build
on : [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello-world"
    - run: ls
    - uses: actions/checkout@v2
    - run: ls
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: docker login 
      run:
        docker login -u hoelito -p +Jazzy2404
